FROM golang:1.24-alpine AS build

WORKDIR /

# Copy source code
COPY [".", "."]

# Download dependencies
RUN ["go", "mod", "download"]

# Build the probe binary
ARG PROBE_VERSION
RUN env CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s -extldflags '-static' -X 'github.com/grafana/nethax/pkg/kubernetes.ProbeImageVersion=${PROBE_VERSION}'" -a -o /probe ./cmd/probe

FROM scratch

COPY --from=build /probe /probe

# Copy CA certificates from build
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

# Set the entrypoint
ENTRYPOINT ["/probe"] 
