FROM --platform=$BUILDPLATFORM golang:1.25-alpine@sha256:d9b2e14101f27ec8d09674cd01186798d227bb0daec90e032aeb1cd22ac0f029 AS build

WORKDIR /

# Copy source code
COPY [".", "."]

# Download dependencies
RUN ["go", "mod", "download"]

ARG PROBE_IMAGE
#  Passed in from buildx
ARG TARGETOS
ARG TARGETARCH
# Build the probe binary
RUN env CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags="-w -s -extldflags '-static' -X 'github.com/grafana/nethax/pkg/kubernetes.DefaultProbeImage=${PROBE_IMAGE}'" -a -o /nethax-probe ./cmd/nethax-probe
RUN env CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s -extldflags '-static' -X 'github.com/grafana/nethax/pkg/kubernetes.DefaultProbeImage=${PROBE_IMAGE}'" -a -o /nethax-probe ./cmd/nethax-probe

FROM scratch

COPY --from=build /nethax-probe /nethax-probe

# Copy CA certificates from build
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

# Set the entrypoint
ENTRYPOINT ["/nethax-probe"]
