FROM --platform=$BUILDPLATFORM golang:1.25-alpine@sha256:352f1ef84634653587abc7f3bdf920eb2a96887a430c23e202a600239eaeedf7 AS build

WORKDIR /

# Copy source code
COPY [".", "."]

# Download dependencies
RUN ["go", "mod", "download"]

# Build the probe binary
ARG PROBE_IMAGE
#  Passed in from buildx
ARG TARGETOS
ARG TARGETARCH
# Build the probe binary
RUN env CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags="-w -s -extldflags '-static' -X 'github.com/grafana/nethax/pkg/kubernetes.DefaultProbeImage=${PROBE_IMAGE}'" -a -o /nethax ./cmd/nethax
RUN env CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s -extldflags '-static' -X 'github.com/grafana/nethax/pkg/kubernetes.DefaultProbeImage=${PROBE_IMAGE}'" -a -o /nethax ./cmd/nethax

FROM scratch

COPY --from=build /nethax /nethax

ENTRYPOINT ["/nethax"]
