FROM golang:1.24-alpine AS build

WORKDIR /

COPY [".", "."]
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags='-w -s -extldflags "-static"' -a -o runner ./cmd/runner

FROM scratch

COPY --from=build /runner /runner

ENTRYPOINT ["/runner"]
