name: Build and Push Image

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          persist-credentials: false
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Dockerhub Login
        uses: grafana/shared-workflows/actions/dockerhub-login@bdb48f8958471b79cdb98c06427126f45e018af5 # dockerhub-login latest
      - name: Enable containerd snapshotting (for multi-platform building)
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d # v5.0.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Build and push
        run: make docker-build docker-push
